execution/src/proof.rs
Fixes #99 
i.e. it now properly rejects proofs where the paths diverge in an extension node.
I also refactored shared_prefix_length a little bit to avoid looping through the node path twice. I added a regression test for the prefix length calculation; testing that the proofs are rejected if the divergent path is found before the end is a bit more complex as I'd have to actually construct a proof like that.
(I still haven't managed to install the deps so that I can actually run the tests, so please bear with me if something doesn't quite build or pass yet - I'll adjust as soon as possible, but I wanted to prioritize PRing the fix)
=> fix: explicit check for invalid divergent paths

Cargo.lock, client/Cargo.toml, client/src/client.rs, client/src/errors.rs, client/src/lib.rs, client/src/node.rs, client/src/rpc.rs, execution/src/errors.rs, execution/src/evm.rs
Surface node errors to RPC.
Also swaps the main `Node.rs` error type to a thiserror NodeError from eyre::Report. For now we wrap many of the underlying erye::Report errors in thiserrors and have to use `.map_err` to convert. As the lower level errors are made more specific these can be automatically wrapped with:
```
#[error(transparent)]
SpecificError(#[from] SpecificUnderlyingThisError)
```
Which will allow removal of the `.map_err` everywhere. (as seen with the existing `BlockNotFoundError`)
Moving to this error handling type will allow consumers of Node (RPC and Client) to surface more specific error details, error types and handling.
=> feat: surface revert errors to RPC

client/src/client.rs, client/src/lib.rs, config/src/lib.rs, config/src/networks.rs, consensus/src/consensus.rs, consensus/src/errors.rs, consensus/tests/sync.rs
Addressing issue #98 
Verifies that the blockhash isn't too old (14 days or older according to the issue) by checking timestamps against the current slot. If it's too old, a timestamp error is thrown
note: also removed `#![feature(map_first_last)]` in `lib.rs` as there were some compiler warnings thrown that this has been implemented in stable releases and is no longer required
=> feat: verify checkpoint has valid age

rust-toolchain
One may install/use `stable` channel by default locally, and will get 
```
error: failed to load manifest for workspace member `/Users/chris/gitfiles/HAOYUatHZ/helios/cli`
Caused by:
failed to parse manifest at `/Users/chris/gitfiles/HAOYUatHZ/helios/cli/Cargo.toml`
Caused by:
the cargo feature `different-binary-name` requires a nightly version of Cargo, but this is the `stable` channel
See https://doc.rust-lang.org/book/appendix-07-nightly-rust.html for more information about Rust release channels.
See https://doc.rust-lang.org/cargo/reference/unstable.html#different-binary-name for more information about using this feature.
```
when compiling this project.
Adding `rust-toolchain` to specify a channel can avoid this problem
=> build: add `rust_toolchain`

Cargo.lock, Cargo.toml, cli/src/main.rs, client/Cargo.toml, client/src/client.rs, client/src/node.rs, client/src/rpc.rs, common/Cargo.toml, config/Cargo.toml, config/src/lib.rs, consensus/Cargo.toml, consensus/src/consensus.rs, consensus/src/rpc/mock_rpc.rs, consensus/src/rpc/mod.rs, consensus/src/rpc/nimbus_rpc.rs, consensus/src/types.rs, consensus/src/utils.rs, execution/Cargo.toml, execution/src/evm.rs, execution/src/execution.rs, execution/src/proof.rs, execution/src/rpc/http_rpc.rs, execution/src/rpc/mock_rpc.rs, execution/src/rpc/mod.rs, execution/src/types.rs, heliosup/heliosup
Fixes all linting errors raised by nightly with
```bash
cargo check --all && cargo +nightly fmt -- --check && cargo +nightly clippy --all --all-features -- -D warnings && cargo test --all --all-features
```
Additionally removes unused cargo packages in subcrates.
This is preparatory work for further contributions @ncitron  😄
=> feat: Lints, Clippy, and Cleaning

src/lib.rs
Currently execution::types::CallOpts is not exported, and it is needed to be able to use call function of Helios client.
- Updated Helios `lib.rs` to export `execution::types::CallOpts`
Closes #117
=> chore: export CallOpts type

Cargo.lock, README.md, cli/src/main.rs, client/src/client.rs, client/src/node.rs, config/Cargo.toml, config/src/base.rs, config/src/checkpoints.rs, config/src/cli.rs, config/src/config.rs, config/src/lib.rs, config/src/networks.rs, config/src/types.rs, config/src/utils.rs, config/tests/checkpoints.rs, consensus/src/consensus.rs
Introduces lazy checkpoint fallback services.
The following two cli flags are introduced in this pr.
- `--fallback` or `-f` sets the checkpoint fallback url (a string). This is only used if the checkpoint provided by the `--checkpoint` flag is too outdated for Helios to use to sync.
If none is provided and the `--load-external-fallback` flag is not set, Helios will error.
For example, you can specify the fallback like so: `helios --fallback "https://sync-mainnet.beaconcha.in"` (or using shorthand like so: `helios -f "https://sync-mainnet.beaconcha.in"`)
- `--load-external-fallback` or `-l` enables weak subjectivity checkpoint fallback (no value needed).
For example, say you set a checkpoint value that is too outdated and Helios cannot sync to it.
If this flag is set, Helios will query all …
=> feat: Checkpoint Fallbacks [RFC]

.github/workflows/benchmarks.yml, .github/workflows/test.yml
Right now, if someone opens up a PR from a fork, the benchmarks will fail. This is because actions triggered from PRs from forks cannot access secrets for security reasons.
One option is to use the `pull_request_target`  trigger, which allows PRs from forks to access secrets. I don't want to do this though in case we add more valuable secrets and forget that this action trigger can expose them to an attacker. Obviously as it stands, I don't really care if someone can steal my alchemy key though.
This PR just switches the benches to a separate action that only triggers on pushes to master. I don't think we often care about the benchmarks for every incoming PR anyway, and we can always manually trigger the benchmark action for a PR if we want.
=> fix(ci): move benchmark ci to seperate action

src/lib.rs
Currently execution::types::ExecutionBlock is not exported, and it is needed to be able to use `get_block_by_<x>` functions of Helios client.
* Updated Helios lib.rs to export `execution::types::{CallOpts, ExecutionBlock}`
Closes https://github.com/a16z/helios/issues/145
=> chore: export ExecutionBlock type

src/lib.rs
Following PR #146, other types need to be exported for external integration.
Currently `execution::types::Transactions` is not exported, and it is needed to be able to use `get_block_by_<x>` functions of Helios client.
To avoid future PRs solving the same problem, I propose to export all types in this file  - i.e. export `Account` and `Transactions`.
* Updated Helios lib.rs to export `execution::types::{Account, CallOpts, ExecutionBlock, Transactions}`
Closes #147
=> chore: export `src/execution` types

execution/src/types.rs
Currently the types in execution::types are not deriving the `Clone` trait. This PR adds `Clone` to the derive traits.
Closes #155
=> feat: make execution types clonable

Cargo.toml, README.md
Using some compiler options I managed to reduce the binary to 5.3MB. I consider the tradeoff for helios strictly in favor of size, as it's greatly increases the accessibility of the light client for it to be embedded in webpages and such. 
With the nightly feature `panic_immediate_abort` the binary size can be further reduced and cut out some more panic string formatting. This provides a nice baseline for further size optimizations.
=> Reduce Binary Size to 5.3mb

client/src/client.rs, client/src/node.rs, client/src/rpc.rs, execution/src/execution.rs, execution/tests/execution.rs
- Add get_transaction_by_block_hash_and_index to client
- Add the same function in node, which calls execution's version of it (get_transaction_by_block_hash_and_index) 
OBS: Decided to implement on execution level and use block data from payload and get_transaction from rpc's
- Implement this new RPC method on RpcInner (the server) by calling into Client::getTransactionByBlockHashAndIndex()
- Added a test for this functionality in execution/tests/execution.rs
Issue: #151
=> RPC call : eth_getTransactionByBlockHashAndIndex Implementation

client/src/client.rs, consensus/src/types.rs
closes #168
addresses #165 but still need to cut a new release
=> fix: deserialize wrapped lc headers correctly

rust-toolchain
Today seems as good a day as any. This will cause reinstallation of the nightly tool chain, and cache misses on first build. I have built locally and run cargo fmt using this toolchain file.
=> fix: specify precise nightly version

Cargo.lock, client/src/database.rs
Fixes regression introduced in #182 where `FileDB` fails to load checkpoint if checkpoint file does not exist.
=> fix: check checkpoint file exists

client/src/client.rs, client/src/database.rs, client/src/node.rs, config/src/base.rs, config/src/config.rs, config/src/networks.rs, config/src/utils.rs
Fixes a regression introduced in #182 where manually specified checkpoints were prioritized less than those fetched by the db.
=> fix: handle checkpoint overrides correctly

execution/src/evm.rs, execution/src/rpc/http_rpc.rs, execution/src/types.rs
**Overview**
Fixes #206 and #205
Marks `CallOpts` `to` field as optional and gracefully handles deserialization for data bytes.
=> Fix: Optional CallOpts Recipient

common/src/errors.rs, execution/src/evm.rs
**Overview**
Attempts to address #153 
Inside a `storage` call to the `ProofDB`, unwraps were being performed for slot queries. This pr introduces a new error type to gracefully bubble up failed storage reads: `SlotNotFoundError`.
=> fix(execution/evm): evm panic on slot not found

Cargo.toml, cli/Cargo.toml, client/Cargo.toml, common/Cargo.toml, config/Cargo.toml, consensus/Cargo.toml, execution/Cargo.toml
Cutting a new minor version for Capella support. We will need to cut one more version before mainnet though since the fork epoch has yet to be announced. In the meantime, this version supports goerli.
=> chore: bump version to 0.3.0

Cargo.lock, Cargo.toml, cli/Cargo.toml, client/Cargo.toml, common/Cargo.toml, config/Cargo.toml, consensus/Cargo.toml, execution/Cargo.toml, execution/src/evm.rs, helios-ts/Cargo.toml
Tokio was erroring with a reactor error. I'm not exactly sure what was causing this. My best guess is that a dependency updated and broke something deep down inside some async rust.
This seems to fix it though.
Also bumped ethers to 2.0.2.
Since this change fixes a bug in 0.3.1, we've bumped to 0.3.2
This doesn't fix the wasm build but we'll deal with that later.
=> feat: fix tokio bug

Cargo.lock, Cargo.toml, cli/Cargo.toml, client/Cargo.toml, common/Cargo.toml, config/Cargo.toml, consensus/Cargo.toml, execution/Cargo.toml
#222 bumps ethers to `2.0.2` which is a major version increase. Since ethers types are used in Helios's public interfaces, this is a breaking change. We should bump the minor version here to reflect that.
=> chore: bump to version 0.4.0

client/src/client.rs
The last checkpoint of the node is only saved on `shutdown` from what I have seen.
But for some applications, like Beerus for instance, we are not always stopped gracefully. Which makes us always sync and we never have checkpoint saved into the `data_dir`.
In this PR, I refactorized the save checkpoint logic in the client into a function `save_last_checkpoint`. This function is called in `shutdown` as before, and after the sync with the node. I am not sure about the side effect of this, but this is working fine for us at this moment.
I kept this function private, but there are side effects I don't see and you do, I can propose:
1. Remove the call to `save_last_checkpoint` I made.
2. Make `save_last_checkpoint` public to let the library user decides when to save the checkpoint? Or there is …
=> feat: save checkpoint after sync

.github/workflows/release.yml, heliosup/heliosup
This PR adds a new build target for the release workflow targeting `armv7l`. This is the standard architecture for all non-64 bit Raspberry Pis, and other microcomputers.
This build was tested against a Raspberry Pi running Raspberry Pi OS (fka Raspbian) Bullseye. 
Note that very old Raspberry Pis may be running Raspbian Buster (the older version of the OS), and targeting them is possible when the version of `GLIBC` the builder VM is running is `2.28` (tested by building locally with `cross-rs` and run on Raspbian Buster). This would require a self-hosted runner for Github Actions, as the oldest version of Ubuntu that GA supports out of the box is 20.02, which is being used here.
If your Raspberry Pi is using Buster (check using `cat /etc/os-release`), consider upgrading to Bullseye with …
=> feat: adding support for 32-bit ARM architectures

consensus/src/rpc/nimbus_rpc.rs
https://github.com/a16z/helios/blob/6bc43bd81b325c3f637714d79401b4420a437839/consensus/src/rpc/nimbus_rpc.rs#L52-L61
Since we have the ownership of the response, we can simply consume it instead of cloning.
=> Avoid unnecessary clone in NimbusRPC's `get_updates`

client/src/client.rs, client/src/node.rs, client/src/rpc.rs, execution/src/execution.rs, execution/src/rpc/http_rpc.rs, execution/src/rpc/mock_rpc.rs, execution/src/rpc/mod.rs, execution/tests/execution.rs
Contributes to #200 . Adds
- `eth_getFilterChanges`
- `eth_uninstallFilter`
- `eth_getNewFilter`
- `eth_getNewBlockFilter`
- `eth_getNewPendingTransactionFilter`
@ncitron wanted your thoughts on adding tests. Some of these are just wrappers around ethers::providers.
=> feat(rpc): Add filter rpc endpoints

.github/workflows/release.yml
Github doesn't like it when a tag is a valid commit hash, so we prepend `nightly` to the front of the tag name.
=> fix: use valid nightly release tags

consensus/src/types/utils.rs, helios-ts/index.html, helios-ts/lib.ts
Some transactions fields aren't being populated correctly. It turn out just rlp decoding the transaction is not sufficient. This bug was introduced during previous refactoring so is only present in 0.5.0. We should cut a new release to fix since this is a fairly major bug.
=> fix: populate missing tx fields

Cargo.lock, Cargo.toml, config/Cargo.toml, config/src/checkpoints.rs, consensus/Cargo.toml, consensus/src/rpc/nimbus_rpc.rs
Most retry libraries don't have good enough wasm support to handle executing in a webworker. I wrote a new retry crate called [retri](https://github.com/ncitron/retri) that uses [zduny-wasm-timer](https://github.com/zduny/wasm-timer) internally which has supports both non wasm, browser wasm, and webworker wasm environments.
=> fix: use wasm compatible rpc retries

client/src/client.rs
Hello,
while updating [HeliosKit](https://github.com/rkreutz/HeliosKit) I've noticed that `rpc_bind_ip` is not accessible from `ClientBuilder`, only way to inject it into the builder would be to serialise the config with the binding IP which might be cumbersome, exposing it directly through the builder makes it easier to override.
=> Exposing rpc_bind_ip on ClientBuilder

Cargo.lock, Cargo.toml
closes #303 
It turns out revm had some mishaps with their semver versioning, so for now we need to use github to point to 03.3 which will ensure all of revm's internal dependencies get resolved correctly.
=> fix: use github for revm dependency

examples/call.rs
add `dotenv().ok();` in order to read env variables from .env located in the current project folder.
=> fix(example/call): read local env variables via dotenv

Cargo.lock, client/src/client.rs, config/src/config.rs, execution/src/execution.rs, helios-ts/Cargo.toml, helios-ts/index.html, helios-ts/lib.ts, helios-ts/src/lib.rs, helios-ts/src/storage.rs, helios-ts/webpack.config.js
resolve: #293 
- added a db that use local storage in helios-ts
Not sure how to test this, I tried to run the `run.sh` but there is network error, it could be my network problem since I am using a vpn
=> feat: add local storage cache

config/src/checkpoints.rs, config/src/networks.rs
Without `SEPOLIA` in the list of networks, the call `CheckpointFallback::get_healthy_fallback_services` fails for `networks::Network::SEPOLIA`.
=> Add `SEPOLIA` to `CheckpointFallback` networks

config/src/checkpoints.rs, config/tests/checkpoints.rs, examples/checkpoints.rs
The closure of the Goerli testnet prevents some related tests and examples from passing.
Replacing them with sepolia and holesky
=> fix: replace the unavailable goerli testnet part with sepolia and holesky

Cargo.lock, Cargo.toml, cli/Cargo.toml, client/Cargo.toml, client/src/rpc.rs, config/Cargo.toml, consensus/Cargo.toml, helios-ts/Cargo.toml
This PR updates most of the dependencies to its newest versions.
Only `jsonrpsee` hasn't been updated to the newest version as it requires a bigger refactor, but I bumped it a few versions anyway.
=> update dependencies to newest versions

README.md
The All that Node Ethereum RPC URLs are changed. So I created a pull request.
I have a question. Does the helios keep support `goerli` network in this project? 
Because the All That Node deprecated the goerli testnet.
=> docs: fix allthatnode ethereum mainnet rpc url

Cargo.lock, Cargo.toml
Bump revm revision to 50726f3e1b2f7b4d50f6755ed30a1ae3108583bf to include bluealloy/revm#837 and fix #337.
=> fix(example/call): bump revm version fixes #337

Cargo.toml, client/src/client.rs, client/src/node.rs, client/src/rpc.rs, common/src/types.rs, consensus-core/src/types/utils.rs, examples/call.rs, execution/src/evm.rs, execution/src/rpc/http_rpc.rs, execution/src/rpc/mock_rpc.rs, execution/src/rpc/mod.rs, execution/src/types.rs, helios-ts/src/lib.rs, src/lib.rs
Makes `eth_call` more robust and partially addresses #346
=> feat: use full tx request in call

benches/file_db.rs, benches/get_balance.rs, benches/get_code.rs, benches/harness.rs, benches/sync.rs
**Description**
- Due to the migration from `ether-rs` to `Alloy `and changes in some basic API parameter types, the benchmark part was unable to run properly. 
- **This PR fixes the tests for file_db.** 
- The other benchmark tests involve changes related to the testnet, which would require more extensive modifications. Since the file_db test does not involve network requests, it is submitted as a separate PR
**Local test result**
=> fix: make file_db benchmark runable

consensus-core/src/types/mod.rs
This `Serialize` bound was removed in https://github.com/a16z/helios/pull/356, but is necessary to convert the `LightClientStore` into bytes, which is used in https://github.com/succinctlabs/sp1-helios/.
=> chore: serialize lc store

README.md
Since the Goerli testnet was replaced by [Holesky testnet ](https://github.com/eth-clients/holesky) for a while, I would suggest updating the Goerli-related docs and example code to the Holesky version.
The updated example code works well on my local PC.
=> docs: update Goerli-related docs to Holesky

.github/workflows/release.yml, Cargo.lock, client/Cargo.toml, client/src/errors.rs, client/src/rpc.rs, heliosup/heliosup
Depends on #372.
Part of #370.
=> Release the linux riscv64gc version

ethereum/src/consensus.rs
=> fix: save every new checkpoint

core/src/client/mod.rs
This PR fixes #380
I have updated the function to return correct value and call the correct function.
Working locally ✅
=> fixes #380 | fixes get_filter_changes() function

README.md, helios-ts/index.html, helios-ts/src/opstack.rs, opstack/src/config.rs, opstack/src/server/net/bootnodes.rs
Closes https://github.com/a16z/helios/issues/421
=> chore: rename optimism to op-mainnet

core/src/client/mod.rs, core/src/client/node.rs, core/src/client/rpc.rs, core/src/execution/errors.rs, core/src/execution/mod.rs, core/src/execution/rpc/http_rpc.rs, core/src/execution/rpc/mock_rpc.rs, core/src/execution/rpc/mod.rs, helios-ts/lib.ts, helios-ts/src/ethereum.rs, helios-ts/src/opstack.rs, rpc.md, tests/rpc_equivalence.rs
Partially Closes: #200.
Related: https://github.com/a16z/helios/issues/200#issuecomment-2460454087
=> feat: implement eth_getBlockReceipts

helios-ts/lib.ts, helios-ts/src/ethereum.rs, helios-ts/src/opstack.rs, rpc.md
Closes #233.
Changes:
- Expose `eth_getTransactionByHash` and `eth_getTransactionByBlockHashAndIndex` in the helios-ts provider.
- Add info on `eth_getTransactionByHash` and `eth_getTransactionByBlockHashAndIndex` in rpc.md
=> fixes #233: eth_getTransactionByHash & eth_getTransactionByBlockHashAndIndex in helios-ts provider

helios-ts/lib.ts
This fixes a typo (missing `{`) introduced in https://github.com/a16z/helios/pull/425.
=> fix: missing parentheses in helios-ts/lib.ts

core/src/execution/errors.rs, core/src/execution/mod.rs
Closes #438.
**Changes:**  
- Optimize the process of fetching transaction receipts in `verify_logs` method by using `eth_getBlockReceipts` to retrieve all receipts for a block in a single request, instead of calling `eth_getTransactionReceipt` for each transaction individually.
**Notes:**  
- This optimization may allow for increasing the value of the `MAX_SUPPORTED_LOGS_NUMBER` constant.  
- Attempted adding a `test_get_logs` method in `rpc_equivalence.rs` tests, but faced issues with flakiness. Can't really have deterministic log filtering since these tests always query the `latest` block from the RPC. Open to suggestions here.
=> perf: use get_block_receipts in verify_logs

core/src/client/mod.rs, core/src/client/node.rs, core/src/client/rpc.rs, core/src/execution/evm.rs, core/src/execution/mod.rs, helios-ts/src/ethereum.rs, helios-ts/src/opstack.rs
=> fix: return null from getBlockTransactionCount methods for unsynced block

core/src/client/mod.rs, core/src/client/node.rs, core/src/client/rpc.rs, core/src/execution/mod.rs, core/src/execution/state.rs, helios-ts/lib.ts, helios-ts/src/ethereum.rs, helios-ts/src/opstack.rs, rpc.md
=> feat: implement eth_getTransactionByBlockNumberAndIndex

README.md
This PR addresses the following issues in the `README.md` file:  
1. Corrected the usage of "a" to "an" for proper grammar in the phrase "an Execution Layer block hash."  
2. Ensured consistent spelling of "finalized" across the document, replacing "finalised" for uniformity.  
- Replaced "a Execution Layer block hash" with "an Execution Layer block hash."  
- Standardized the spelling of "finalized" to ensure consistency.  
These changes enhance the readability and grammatical accuracy of the documentation.
=> Fix grammatical consistency and improve spelling in README.md

opstack/src/consensus.rs
Corrected `finalied_block_recv` to `finalized_block_recv` x2
=> fix: typos in documentation files

Cargo.lock, cli/Cargo.toml, cli/src/main.rs, ethereum/Cargo.toml, ethereum/src/config/cli.rs
partially towards #474 
replaces string type to url in cli. There are other places this type change can be implemented, will raise similar small PRs towards #474
=> refactor: change rpc from string to url in cli entrypoint

.codespellrc, .github/workflows/codespell.yml
This pull request integrates a CI step to automate typo detection using `codespell`. The workflow is configured to run on pull requests and pushes to the `ci-typos` branch. It includes:  
- A `.codespellrc` file to customize ignored words and skipped file types.  
- A GitHub Actions workflow (`codespell.yml`) to install and execute `codespell`.  
This integration aims to enhance code quality by preventing typographical errors in the repository.
=> feat: add CI for Typo Checking

ethereum/src/rpc/http_rpc.rs
Without this fix, helios doesn't work when `--consensus-rpc` is given:
```
$ cargo run -- ethereum --rpc-port 14433 --network mainnet --execution-rpc https://ethereum-rpc.publicnode.com --consensus-rpc https://ethereum.operationsolarstorm.org
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.40s
Running `target/debug/helios ethereum --rpc-port 14433 --network mainnet --execution-rpc 'https://ethereum-rpc.publicnode.com' --consensus-rpc 'https://ethereum.operationsolarstorm.org'`
2025-01-08T02:21:17.908637Z  INFO helios::rpc: rpc server started at 127.0.0.1:14433
2025-01-08T02:21:18.591966Z ERROR helios::consensus: sync failed err=could not fetch bootstrap: rpc error on method: bootstrap, message: status: 404, raw response: b""
```
=> fix: Trim the ending slash from consensus RPC

Cargo.lock, Cargo.toml, core/src/execution/mod.rs, core/src/execution/rpc/http_rpc.rs, core/src/types.rs, ethereum/consensus-core/Cargo.toml, ethereum/src/consensus.rs, ethereum/src/spec.rs, helios-ts/Cargo.toml, helios-ts/src/opstack.rs, opstack/Cargo.toml, opstack/src/consensus.rs, opstack/src/spec.rs, tests/rpc_equivalence.rs
This is my take on issue #484 . I tried to keep it as simple as possible without any rework of underlying structure.
Key changes:
`alloy` crates have been updated to latest version of `9.0`
Some breaking changes are likely to be introduced because of change `TransactionRequest` -> `OpTransactionRequest` type for OPStack.
I invite anyone interested to review and regression test this PR, feedback is much appreciated. I'd be happy to fix whatever has to be fixed.
=> chore: update alloy version to 9.0

helios-ts/lib.ts
fixes: #496
After latest changes, `Block` is serialized differently which results in `Map` in JavaScript. This is not an expected type from a provider.
This PR uses existing `mapToObj` function to process the `Map` into an `Object`.
=> Fix: process Map into an Object for blocks in helios-ts

core/src/execution/mod.rs, core/src/execution/proof.rs, opstack/src/consensus.rs
Follow up to #506.
Closes #503.
=> fixes #503: handle empty account or storage value in proof verification

Cargo.lock, ethereum/Cargo.toml
I have a build error in latest helios here:
https://github.com/a16z/helios/blob/d35a0b7e776b6284cf3ec042f96df17ae90f0239/ethereum/src/config/cli.rs#L10-L13
because the `url` serde feature is not enabled. So I added it.
=> fix: add serde feature for url

core/src/execution/state.rs
fixes #501 
There's little need to push finalized blocks into `blocks` state because they would either repeat existing blocks, or cause unexpected backfills. Thus, I suppose we can remove this step.
=> fix: #501 accidental blocks backfill due to a race condition

core/src/execution/mod.rs, core/src/execution/proof.rs
This fixes a bug introduced in PR #507.
- The `ensure_logs_match_filter` fn was not handling the null case for filter topics.
- Removed the unnecessary `async` on `ensure_logs_match_filter` fn.
=> fix: handle empty filter topic in ensure_logs_match_filter

ethereum/consensus-core/src/consensus_core.rs, ethereum/src/consensus.rs
Ref #388 
Run the following command to check that the issue is resolved:
```
cargo run ethereum --execution-rpc 'https://eth-mainnet.g.alchemy.com/v2/<API_KEY>' --checkpoint 0xc7fc7b2f4b548bfc9305fa80bc1865ddc6eea4557f0a80507af5dc34db7bd9ce
```
=> bug fix: Sync failing for checkpoint > 128

ethereum/src/consensus.rs, ethereum/src/rpc/mock_rpc.rs, tests/rpc_equivalence.rs
-  fixes tests failures from #528 making the mock rpc act strange
- disables rpc equivalence tests when rpc url is not available so we don't miss test failures in the future
=> fix: consensus tests

ethereum/consensus-core/src/consensus_core.rs, ethereum/consensus-core/src/consensus_spec.rs, ethereum/consensus-core/src/types/mod.rs, ethereum/src/consensus.rs
This PR just fixes two typos found by [typos](https://crates.io/crates/typos), nothing fancy.
The `typos` check can also be integrated into the CI pipeline (as in https://github.com/a16z/jolt/pull/597):
```
jobs:
...
typos:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v3
- uses: crate-ci/typos@v1
with:
files: .
```
=> chore: fix typos

helios-ts/lib.ts
1. Fixed duplicate method: Removed the redundant `"eth_getTransactionByHash"` case in `#req()`, preventing potential conflicts.
2. Improved error handling: Changed `throw "invalid kind: must be ethereum or opstack";` to `throw new Error("Invalid kind: must be 'ethereum' or 'opstack'");` for better stack trace support.
=> Fix duplicate method and improve error handling in HeliosProvider

benches/harness.rs
I found that the address in the comment has expired, the purpose of this PR is to fix this problem
=> chore: fix 404 status URL

README.md, ethereum/src/config/checkpoints.rs
Old:
cause Helios and over light clients to sync incorrectly
New:
cause Helios and other light clients to sync incorrectly
Reason: The word “over” appears to be a typographical error. Replacing it with “other” correctly refers to additional light clients besides Helios.
Old:
These services are not healthchecked **nor** trustworthy...
New:
These services are not health-checked **nor** trustworthy...
Reason: “health-checked” is the proper hyphenated adjective form.
=> Fix Minor Grammar Errors

Cargo.lock, common/Cargo.toml, common/src/types.rs, core/src/client/mod.rs, core/src/client/node.rs, core/src/client/rpc.rs, core/src/execution/mod.rs, core/src/execution/state.rs, helios-ts/lib.ts, helios-ts/package-lock.json, helios-ts/package.json, helios-ts/src/ethereum.rs, helios-ts/src/lib.rs, helios-ts/src/opstack.rs, helios-ts/src/subscription.rs, rpc.md
closes #302
This PR implements a subscription (Pub/Sub) pattern for Helios:
- [EIP-1193](https://eips.ethereum.org/EIPS/eip-1193#events) compliant events handling for helios-ts acting as an Ethereum provider.
- [Geth real-time events spec](https://geth.ethereum.org/docs/interacting-with-geth/rpc/pubsub#cancel-subscriptions) compliant for RPC server mode via WebSocket connection (connection and subscription lifecycle are handled by jsonrpsee)
Currently only `hewHeads` event type is implemented by broadcasting latest blocks pushed to Helios's inner state (ignoring backfills).
Note: when RPC providers are slow or we have a slow machine, some blocks can be missed, especially in WASM mode. This is generally in line with Geth spec: *Notifications are sent for current events and not for past …
=> feat: implement subscription for newHeads

opstack/src/spec.rs
=> fix: panic when transaction env is built for opstack

Cargo.lock, core/src/execution/evm.rs
Some evm executions get stuck in an infinite loop when it needs to fetch slot a and b but does not realize it at the same time. This leads to fetching a, then fetching b (and evicting a from our state cache), leading to fetching a again, and repeating the cycle.
=> fix: evm state fetch infinite loop

verifiable-api/server/openapi.yaml
Fixed a link to GitHub repository in verifiable-api/server/openapi.yaml, 
which contained duplicate square and parentheses. As a result of the 
fix, the documentation will display correctly and links will work properly.
Modified file:
- verifiable-api/server/openapi.yaml
=> fix: fixed incorrectly formatted link in OpenAPI documentation

.github/workflows/release.yml
Ubuntu 20.04 was deprecated by GitHub so broke our release CI on linux-armv7. Updating to ubuntu-latest seems to resolve.
=> fix: update armv7 build to use latest ubuntu

benches/README.md
Fixed documentation links in `benches/README.md`:
- Updated the link to Cargo.toml from `./Cargo.toml` to `../Cargo.toml`
- Updated the link to the client example from `./examples/client.rs` to `../examples/client.rs`
The previous ones were broken.
=> fix: hyperlinks to Cargo.toml and client.rs

.github/workflows/benchmarks.yml, .github/workflows/codespell.yml, .github/workflows/test.yml
Hey ! GitHub‑hosted runners now use Node 20, so checkout v4 is required
This PR updates all workflows to actions/checkout@v4 , no functional changes expected
=> ci: bump actions/checkout to v4

Cargo.lock, Cargo.toml, common/src/network_spec.rs, core/src/execution/client/rpc.rs, core/src/execution/errors.rs, core/src/execution/evm.rs, core/src/execution/mod.rs, core/src/execution/proof.rs, core/src/execution/rpc/http_rpc.rs, ethereum/consensus-core/Cargo.toml, ethereum/consensus-core/src/proof.rs, ethereum/src/consensus.rs, ethereum/src/spec.rs, linea/src/consensus.rs, opstack/Cargo.toml, opstack/src/consensus.rs, opstack/src/spec.rs, tests/rpc_equivalence.rs
In the process of bumping SP1 dependencies to `v4.2.0` in sp1-helios, I came accross the following error:
```
error: failed to select a version for `c-kzg`.
... required by package `alloy-consensus v0.14.0`
... which satisfies dependency `alloy-consensus = "^0.14"` of package `alloy v0.14.0`
... which satisfies dependency `alloy = "^0.14.0"` of package `sp1-helios-script v0.1.0 (/home/aurel/dev/sp1-helios/script)`
versions that meet the requirements `^2.1` are: 2.1.1, 2.1.0
the package `c-kzg` links to the native library `ckzg`, but it conflicts with a previous package which links to `ckzg` as well:
package `c-kzg v1.0.3`
... which satisfies dependency `c-kzg = "^1.0.3"` of package `revm-precompile v16.2.0`
... which satisfies dependency `revm-precompile = "^16.2.0"` of package `revm …
```
=>  chore: bump Alloy, Revm and a few other crates

rpc.md
Replaced the outdated link to the Ethereum JSON RPC specification (https://ethereum.github.io/execution-apis/api-documentation) with the current official documentation URL (https://ethereum.org/en/developers/docs/apis/json-rpc/) in the rpc.md file. This ensures users are directed to the most up-to-date and maintained resource. No other content was changed.
=> Update Ethereum JSON RPC Spec link to the latest official documentation

ethereum/src/config/networks.rs
A minimal addition of Ethereum's Hoodi test network.
- Network metadata pulled from here: https://github.com/eth-clients/hoodi/tree/main?tab=readme-ov-file#metadata 
- Default checkpoint pulled from "Latest Finalised" here: https://checkpoint-sync.hoodi.ethpandaops.io/ 
- Fork versions pulled from: https://github.com/eth-clients/hoodi/blob/main/metadata/config.yaml 
Related to https://github.com/a16z/helios/issues/101
=> Add Ethereum's hoodi test network

core/src/client/node.rs, ethereum/src/consensus.rs, linea/src/consensus.rs, opstack/src/consensus.rs
This PR improves the logging system in Helios to provide more uniform and cleaner logging output for block updates.
- **Unified logging location**: Moved block sync logging from individual consensus modules to helios-core for consistency
- **Cleaner log format**: 
- Latest blocks: `latest block     number=X age=Xs`
- Finalized blocks: `finalized block  number=X`
- **Reduced noise**: Changed consensus module logs from info to debug level
- **Deduplication**: Added tracking to prevent duplicate finalized block logs
- **Better alignment**: Block numbers are aligned between latest and finalized logs for easier reading
```
INFO helios::consensus: finalized slot             slot=10406016  confidence=100.0%  age=00:00:04:00
INFO helios::consensus: updated head               slot=10406048 …
```
=> chore: improve logging system for block updates

Cargo.lock, ethereum/Cargo.toml, ethereum/src/consensus.rs
- Addresses sync delay issues by parallelizing CPU-intensive transaction signature recovery operations
- Moves signature recovery work off the async runtime to prevent blocking
- Significantly improves block processing performance during sync
- Added `rayon` dependency for parallel processing on native platforms
- Modified `payload_to_block` function to use `tokio::task::spawn_blocking` for async compatibility
- Implemented parallel transaction processing using rayon's parallel iterator
- Increased thread pool stack size to 4MB to handle signature recovery operations
- Maintained sequential processing on WASM targets for compatibility
The signature recovery process is one of the most CPU-intensive operations during block processing. By parallelizing this work across multiple threads, we …
=> perf: parallelize transaction signature recovery to reduce sync delays

helios-ts/README.md, helios-ts/index.html, helios-ts/lib.ts, helios-ts/package-lock.json, helios-ts/tsconfig.json
- Simplified Helios TypeScript initialization by introducing automatic WASM initialization
- Added `createHeliosProvider` function as the primary entry point for creating providers
- Made `HeliosProvider` constructor private to enforce proper initialization pattern
- **New API**: Added `createHeliosProvider` async function that handles WASM initialization internally
- **Automatic initialization**: Implemented singleton pattern to ensure WASM is initialized only once
- **Private constructor**: Made `HeliosProvider` constructor private and added static `create` method
- **Documentation updates**: Updated README.md with clearer examples using the new API pattern
- **Demo updates**: Updated index.html to demonstrate the new initialization approach
- **Package metadata**: Fixed package name …
=> refactor: improve TypeScript initialization API

ethereum/src/consensus.rs, helios-ts/index.html
- Removed tokio::task::spawn_blocking usage in consensus module for payload_to_block conversions
- Fixes WASM compatibility issues since spawn_blocking is not supported in WASM environments
- **consensus.rs**: Removed spawn_blocking wrappers around payload_to_block calls
- The function is now called directly, simplifying the code
The `tokio::task::spawn_blocking` function is designed to move CPU-intensive work off the async runtime to dedicated threads. However, this functionality is not available in WASM environments which don't have access to OS-level threads. By removing these spawn_blocking calls, the code now works correctly in both native and WASM builds.
=> fix: remove spawn_blocking for payload_to_block conversions

core/src/client/mod.rs, ethereum/src/config/checkpoints.rs, verifiable-api/client/src/http.rs
- Fixes unused import warnings when building for WASM targets
- Adds conditional compilation attributes to imports only used in non-WASM code paths
- **core/src/client/mod.rs**: 
- Conditionally import `SocketAddr` with `#[cfg(not(target_arch = "wasm32"))]`
- Move `inner_ref` clone inside the non-WASM block where it's used
- **ethereum/src/config/checkpoints.rs**: 
- Conditionally import `Duration` which is only used in non-WASM code
- **verifiable-api/client/src/http.rs**: 
- Conditionally import `Duration`
- Scope `client_ref` and `base_url_str` variables inside non-WASM block
This change eliminates compiler warnings when building for WASM targets, improving the development experience and ensuring cleaner builds. No functional changes are made - this is purely a code hygiene …
=> chore: fix unused import warnings in WASM builds

.gitignore
Update .gitignore to exclude various development-related files from version control.
- Added Docker configuration files used for development environments
- Added session tracking and release notes files
- Added worktrees directory exclusion
- Properly formatted existing entries
These files are specific to individual development setups and should not be tracked in the repository to keep it clean and avoid unnecessary commits.
=> chore: update gitignore with development files

Cargo.lock, core/src/execution/providers/rpc.rs, core/src/execution/providers/utils.rs, core/src/execution/providers/verifiable_api.rs
This PR fixes an issue where block tag queries (Latest, Safe, Finalized, etc.) were being routed to historical providers, which could return outdated information. Historical providers should only be used for specific block numbers or hashes.
- Added `should_use_historical_provider` utility function to determine when to use historical providers
- Updated `rpc.rs` to use the new utility function instead of checking only for Latest
- Updated `verifiable_api.rs` to use the same logic for consistency
- Historical providers are now only used for:
- Specific block numbers (BlockId::Number with a numeric value)
- Block hashes (BlockId::Hash)
- Block tags (Latest, Safe, Finalized, Pending, Earliest) now always use the current provider
=> fix: prevent historical provider queries for block tags

ethereum/consensus-core/Cargo.toml
Since Alloy v0.11, there is a new default `essentials` feature, that add a dependency to `alloy-provider`, that in turn bring Tokio in the dependency tree.
This cause build to fail in the sp1-helios zkVM client program because it has a dependency to `helios-consensus-core` that bring the above.
So I added  `default-features = false` to `helios-consensus-core` Alloy dep.
=> fix: disable alloy default features on helios-consensus-core

cli/src/tui/app.rs, cli/src/tui/mod.rs, cli/src/tui/ui.rs, ethereum/src/config/networks.rs, ethereum/src/evm.rs, ethereum/src/rpc/mock_rpc.rs, helios-ts/src/ethereum.rs, helios-ts/src/linea.rs, helios-ts/src/opstack.rs, opstack/src/evm.rs, opstack/src/server/net/block_handler.rs, verifiable-api/client/src/http.rs
- Updated format\! macro calls to use inline variable syntax as recommended by latest Rust clippy lints
- Replaced manual parameter passing with cleaner inline formatting across multiple modules
- Improves code readability and follows modern Rust conventions
- Updated format\! calls in cli/src/tui modules
- Fixed string formatting in ethereum/src modules
- Updated opstack/src modules to use inline variables
- Applied consistent formatting in verifiable-api/client/src/http.rs
=> chore: update string formatting to use inline variables

ethereum/src/evm.rs, opstack/src/evm.rs, tests/rpc_equivalence.rs
This PR fixes a panic in `get_context` that occurred when the underlying `get_block` call either returned an error or `None`.
Previously, `get_context` called `.unwrap()` on the result of `get_block`, which caused to panic
- **ethereum/src/evm.rs**: 
- Modified `get_context()` to return `Result<Context, EvmError>`
- Replaced `.unwrap()` calls with proper error handling using `map_err()` and `ok_or_else()`
- Updated `transact_inner()` to handle the `Result` from `get_context()`
- Existing tests don’t explicitly cover `get_context` failure paths; I would appreciate any feedback on how to handle this.
- This PR does not change the behavior of `get_block` or `get_historical_block`, and respects the existing context where `None` indicates a missing block.
Fixes #627
=> Fix: avoid panic in `get_context` when `get_block` returns error or None

Cargo.lock, common/src/execution_provider.rs, common/src/network_spec.rs, core/src/client/mod.rs, core/src/client/node.rs, core/src/execution/providers/rpc.rs, core/src/execution/providers/verifiable_api.rs, ethereum/src/evm.rs, ethereum/src/spec.rs, opstack/src/evm.rs, opstack/src/spec.rs, revm-utils/src/proof_db.rs
- Fixed typo in trait name from `ExecutionProivder` to `ExecutionProvider`
- Updated all implementations and references across the codebase
- No functional changes, purely a naming correction
- Renamed trait from `ExecutionProivder` to `ExecutionProvider` in `common/src/execution_provider.rs`
- Updated all trait implementations in:
- `common/src/network_spec.rs`
- `core/src/client/mod.rs` and `core/src/client/node.rs`
- `core/src/execution/providers/rpc.rs` and `core/src/execution/providers/verifiable_api.rs`
- `ethereum/src/evm.rs` and `ethereum/src/spec.rs`
- `opstack/src/evm.rs` and `opstack/src/spec.rs`
- `revm-utils/src/proof_db.rs`
=> fix: correct ExecutionProvider trait name typo

ethereum/src/rpc/http_rpc.rs
- Adds proper timeout configuration to the HTTP client in `HttpRpc` to prevent indefinite hangs
- Fixes issue where Helios could freeze when running for extended periods
When running Helios (specifically with Ethereum) for long periods, it sometimes freezes and stops following the chain. Analysis revealed that the HTTP client could hang indefinitely on network requests if the beacon node becomes unresponsive or network issues occur.
Added timeout configuration to the reqwest HTTP client:
- **Request timeout**: 30 seconds - prevents individual requests from hanging indefinitely
- **Connection timeout**: 10 seconds - ensures connection establishment doesn't block forever  
- **Idle connection cleanup**: 60 seconds - prevents resource exhaustion from stale connections
=> fix: add timeouts to HTTP client to prevent freezing

Cargo.lock, ethereum/consensus-core/Cargo.toml, ethereum/consensus-core/src/types/mod.rs, ethereum/consensus-core/tests/slot_12557247_rpc_test.rs
- Fixed incorrect variant ordering in superstruct definitions causing tree hash mismatches
- Reordered Electra variant to be listed before Base variant in both IndexedAttestation and Attestation types
- Added test case to verify correct tree hash calculation for beacon blocks
The tree hash calculation for beacon blocks was failing because the superstruct variants for IndexedAttestation and Attestation types were ordered incorrectly. The Base variant was listed first, but the Electra variant needs to be first for proper deserialization and hash calculation.
Reordered the superstruct variants in both `IndexedAttestation` and `Attestation` types to list Electra before Base. This ensures that during deserialization, the correct variant is selected and the tree hash is calculated properly.
- …
=> fix: resolve tree hash calculation for IndexedAttestation and Attestation types

.github/workflows/release.yml, .github/workflows/test.yml, helios-ts/package-lock.json, helios-ts/package.json, scripts/check-version-consistency.sh
- Bump up package.json version
- Add consistency check script to be run in github workflows
=> Fix TS package version inconsistency
