a16z/helios

README.md
- mention eth_getProof requirement for eth1 rpc (thanks @lightclient for pointing this out)
- italicize disclaimer
=> documentation: update readme

client/src/client.rs, client/src/node.rs, client/src/rpc.rs, execution/src/errors.rs, execution/src/evm.rs, execution/src/execution.rs, execution/src/rpc/http_rpc.rs, execution/src/rpc/mock_rpc.rs, execution/src/rpc/mod.rs, execution/testdata/logs.json, execution/tests/execution.rs
Fixes issue: https://github.com/a16z/helios/issues/23
This PR is still in draft.
I was wondering if we need any kind of "proof" for logs as we do for account details ?
=> feat: add `get_logs` RPC method

client/src/rpc.rs
=> fix: remove leading zeros in rpc responses

client/src/client.rs, client/src/rpc.rs, common/src/utils.rs, config/src/lib.rs
Introduces websocket support on both the client (starts a ws server) side and the rpc-side.
=> feat: Client + RPC Websocket Support

.github/workflows/test.yml
TODO:
migrate to `Swatinem/rust-cache@v2` after merging https://github.com/a16z/helios/pull/123
=> build(github CI): add cargo clippy

Cargo.lock, Cargo.toml, README.md, client/src/client.rs, config/src/checkpoints.rs, config/src/cli.rs, examples/checkpoints.rs, examples/client.rs, examples/config.rs, src/lib.rs
Introduces examples in `examples/` and defines them at the workspace level in the root `Cargo.toml`.
For example, you can run `cargo run --example checkpoints` to run the `examples/checkpoints.rs` example.
=> feat(examples): Introduces working examples

Cargo.lock, Cargo.toml, client/Cargo.toml, client/src/rpc.rs, common/Cargo.toml, common/src/types.rs, common/src/utils.rs, config/Cargo.toml, config/src/checkpoints.rs, config/src/config.rs, config/tests/checkpoints.rs, consensus/Cargo.toml, consensus/src/consensus.rs, examples/checkpoints.rs, examples/config.rs, examples/readme.rs, execution/Cargo.toml, execution/src/proof.rs, execution/tests/execution.rs
Resolves dependency type conflicts between `revm` and `ethers`. Fixes #127
=> fix(readme): Resolve Dependency Type Conflicts

README.md, rpc.md
PR for RPC documentation given issue #135 
- Adding a rpc.md with a table of supported rpc methods.
- Linking to the rpc.md from readme.md
=> RPC Documentation

.github/workflows/test.yml, .gitignore, Cargo.lock, Cargo.toml, README.md, benches/file_db.rs, benches/get_balance.rs, benches/get_code.rs, benches/harness.rs, benches/sync.rs, client/src/database.rs, config/src/checkpoints.rs
Introduces criterion statistical benchmarking as well as iai one-shot cachegrind benchmarking.
Additionally, fixes a `Checkpoint` issue where unhealthy services prevent successful checkpoint fetches.
- `benches/file_db.rs`: benchmarks reading and writing to the `FileDB`
- `benches/get_balance.rs`: benchmarks fetching account balances on goerli and mainnet.
- `benches/get_code.rs`: benchmarks fetching address code on goerli and mainnet.
_For "known" checkpoint, we fetch the latest checkpoint outside the bench_
=> feat(benches): Criterion + Iai Benchmarking [RFC]

README.md, config.md
Introduces comprehensive documentation of config file options.
=> feat(docs): Config

src/lib.rs
Added "checkpoints" to config module exports
I saw there were some more modules in config, so if there are more that needs to be added please let me know.
Issue: #150
=> chore: add checkpoints in export config mod

execution/src/evm.rs
addresses the first part of #158
=> fix: handle calls to eoa

client/src/client.rs, client/src/node.rs, client/src/rpc.rs
- Implemented get_coinbae Rpc method
=> RPC call : eth_coinbase Implementation #157

Cargo.lock, cli/src/main.rs, client/src/errors.rs, client/src/node.rs, execution/src/errors.rs, execution/src/execution.rs, execution/src/rpc/http_rpc.rs, execution/src/rpc/mock_rpc.rs, execution/src/rpc/mod.rs
Partially addresses #175. Still need to handle the same issue on the consensus layer side.
=> feat: check execution rpc network

benches/file_db.rs, benches/harness.rs
=> fix: benches

src/lib.rs
=> Make ConfigDB public

execution/src/execution.rs
This fixes a weird edge case where you omit the `toBlock` parameter in the log filter, which would implicitly specify it as the lastest block. When fetching from the rpc, it can return logs from a block that Helios hasn't seen yet (if it is one block ahead of helios). This is impossible for  Helios to prove. Instead, we make sure to default `toBlock` to the latest block  Helios has seen when it is omitted.
=> fix: prevent logs for unseen blocks

.gitignore, Cargo.lock, helios-ts/Cargo.toml, helios-ts/index.html, helios-ts/lib.ts, helios-ts/package-lock.json, helios-ts/package.json, helios-ts/run.sh, helios-ts/tsconfig.json, helios-ts/webpack.config.js
Using this neat trick to bundle the wasm inside the js file: https://github.com/rustwasm/wasm-pack/issues/831#issuecomment-952310914
=> fix: embedded wasm binary

client/src/rpc.rs
=> fix: correct zero hex formatting

Cargo.lock, Cargo.toml, examples/call.rs, examples/config.rs
**Overview**
Cleans up and adds an `example/call.rs` from #134
=> fix: Cleanup and Call Example

Cargo.lock, Cargo.toml, common/src/errors.rs, examples/call.rs, examples/config.rs, execution/src/evm.rs
reopened to fix git history. originally #210
=> fix: cleanup call example

Cargo.lock, Cargo.toml, cli/Cargo.toml, client/Cargo.toml, common/Cargo.toml, config/Cargo.toml, consensus/Cargo.toml, execution/Cargo.toml
bumps version in prep for new release with armv7 support
=> chore: version bump

cli/src/main.rs, client/src/client.rs, client/src/rpc.rs, config/src/base.rs, config/src/cli.rs, config/src/config.rs, config/src/networks.rs
Added cli support for `--rpc-bind-ip/-b` to set a custom IP for helios to bind to.
fixes https://github.com/a16z/helios/issues/232
=> feat: allow rpc to bind to custom addresses

Cargo.toml
=> fix: release profile on some apple machines

Cargo.lock, Cargo.toml, config/Cargo.toml, config/src/checkpoints.rs, consensus/Cargo.toml, consensus/src/rpc/nimbus_rpc.rs
Retry logic added for consensus & nimbus api calls.
#272
=> Add retry logic for api calls

benches/file_db.rs, benches/harness.rs, benches/sync.rs
This PR fixes the benchmarks , the the structure of the code had changed , and it seems like it wasnt updated
=> fix: bench marks

.env.example, README.md
Relates to PR #262 comment https://github.com/a16z/helios/pull/262#issuecomment-1690908594
=> docs: Update readme with checkpoint information. 

Cargo.lock, cli/Cargo.toml, cli/src/main.rs
=> fix: use env filter compatible with tracing

README.md, config.md
=> fix: typos

Cargo.lock, Cargo.toml, client/src/client.rs, config/src/networks.rs, examples/basic.rs, examples/call.rs
=> feat: add wait_synced method to client

Cargo.lock, cli/src/main.rs, config/Cargo.toml, config/src/base.rs, config/src/cli.rs, config/src/config.rs, config/src/networks.rs
=> fix: ignored config file fields

src/lib.rs
=> dev: expose client for wasm builds

helios-ts/lib.ts, helios-ts/src/lib.rs
=> feat: add waitSynced to typescript bindings

Cargo.lock, Cargo.toml, consensus/src/consensus.rs, helios-ts/Cargo.toml
=> chore: pin ethers version

README.md, config.md
My explanation might not be the best. Feel free to suggest edits. 
Thank you.
Ref: https://github.com/a16z/helios/issues/232
=> chore: add rpc_bind_ip config to docs

examples/checkpoints.rs
sry, missing one commit in the previous PR
=> chore: fix wrong testnet name in the example

Cargo.lock, Cargo.toml, consensus-core/src/types/utils.rs, execution/src/types.rs, tests/rpc_equivalence.rs
Closes #345.
Will follow up with additional tests and fixes to the block data.
=> test: add rpc equivalence tests

client/src/client.rs, client/src/node.rs, client/src/rpc.rs, common/src/utils.rs, examples/basic.rs, execution/src/evm.rs, execution/src/execution.rs, execution/src/rpc/http_rpc.rs, execution/src/rpc/mock_rpc.rs, execution/src/rpc/mod.rs, execution/tests/execution.rs, helios-ts/src/lib.rs
=> refactor: clean up rpc interface

Cargo.lock, Cargo.toml, common/Cargo.toml, consensus-core/Cargo.toml
=> chore: use minimal alloy features in consensus-core

ethereum/src/rpc/http_rpc.rs
[ x ] Ensure that other implementations of the ConsensusRPC spec do not send error messages with status code `200`, or handle them
[ x ] Potentially use untagged enums to respond with more structured error responses so that the code and message can be "bubbled up"
=> feat: handle HTTP errors more gracefully by catching them before deserialization

helios-ts/src/opstack.rs, opstack/src/config.rs
Related https://github.com/a16z/helios/issues/410
The following networks have been added:
- Worlchain
- Unichain
- Zora
=> feat/added op_stack networks

helios-ts/index.html
**Changes:**
- The network name and class names were not matching for OP. Made them both `op-mainnet`.
- Other small typo fixes.
=> fix: optimism -> op-mainnet in helios-ts/index.html

core/src/execution/rpc/http_rpc.rs
=> feat: implement eth_uninstallFilter

core/src/client/mod.rs, core/src/client/node.rs, core/src/client/rpc.rs, core/src/execution/constants.rs, core/src/execution/mod.rs, rpc.md
Ref #200 
Added `eth_blobBaseFee`
=> feat: added eth_BlobBaseFee

helios-ts/lib.ts, helios-ts/src/ethereum.rs, helios-ts/src/opstack.rs
=> fixes #514: add wasm binding for eth_getStorageAt

core/src/execution/evm.rs, core/src/execution/mod.rs, core/src/execution/state.rs, ethereum/consensus-core/src/consensus_core.rs, ethereum/consensus-core/src/types/mod.rs, ethereum/src/builder.rs, ethereum/src/consensus.rs, ethereum/src/spec.rs, helios-ts/src/lib.rs, opstack/src/builder.rs, opstack/src/consensus.rs, opstack/src/lib.rs, opstack/src/server/mod.rs, opstack/src/spec.rs, opstack/src/types.rs
=> chore: fix clippy errors

.github/workflows/test.yml, ethereum/src/consensus.rs, ethereum/tests/checkpoints.rs, examples/basic.rs, examples/call.rs, examples/checkpoints.rs, examples/client.rs, tests/rpc_equivalence.rs
=> chore: fix test ci

opstack/src/builder.rs
=> chore: fix singer -> signer

cli/src/main.rs, opstack/bin/server.rs, verifiable-api/server/bin/server.rs, verifiable-api/server/src/server.rs
ref: https://github.com/a16z/helios/pull/559
```
➜  helios git:(master) ✗ cargo check --features clap/deprecated
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.76s
```
=> fix(all): remove deprecated #[clap] attribute

helios-ts/index.html
=> minor docstring in .html

core/src/client/node.rs, core/src/execution/state.rs
Building on comments from #556, we return zero address for eth_coinbase. Closes #527
=> chore: zero address returned for eth_coinbase

Cargo.lock, Cargo.toml, opstack/src/config.rs, opstack/src/spec.rs
- adds unichain support
- fixes post-isthmus withdrawals root check
=> chore: unichain support

core/src/client/node.rs
Fixes wait_synced method in WASM mode
=> fix: client.wait_synced method in WASM mode

core/src/execution/providers/block/block_cache.rs
This PR implements block consistency validation in the `BlockCache` to ensure Helios maintains a coherent view of the blockchain. When inconsistent blocks are received (due to reorganizations, gaps, or forks), the cache is automatically cleared to prevent serving stale or conflicting data.
- **Parent validation**: Checks that new blocks properly build on existing cached blocks by verifying parent hash relationships
- **Gap detection**: Detects when blocks skip numbers (e.g., receiving block 5 when cache only has blocks 0-2)
- **Fork handling**: Automatically clears cache when blocks from different forks are received
- **Genesis handling**: Special case handling for genesis blocks (block 0)
- **Immutable blocks**: Finalized blocks are preserved during cache clearing since they cannot be …
=> feat: add block consistency validation to BlockCache

.gitignore, Cargo.lock, Cargo.toml, ethereum/src/config/networks.rs, tests/rpc_equivalence.rs, verifiable-api/server/src/handlers.rs
This PR significantly improves the RPC equivalence test suite by introducing parallel execution, better error handling, and real-time test output. The refactoring reduces test execution time by ~85% while improving maintainability and debugging capabilities.
The existing RPC equivalence tests were running sequentially, taking 30-60 seconds to complete. Additionally, test failures would panic, making it difficult to see which specific tests failed in CI environments. This refactoring addresses both performance and debugging concerns.
- **Parallel test execution**: All 34 RPC method tests now run concurrently
- **Single setup phase**: Helios instances are initialized once and shared across all tests
- **Execution time**: Reduced from ~30-60 seconds to ~4-7 seconds (85% improvement)
- …
=> test: refactor rpc equivalence tests for improved performance and error handling

helios-ts/lib.ts, helios-ts/package-lock.json
This PR enhances the TypeScript bindings with comprehensive type definitions and detailed JSDoc documentation to improve the developer experience when using Helios in TypeScript projects.
- Added explicit `NetworkKind` type with supported values: "ethereum", "opstack", and "linea"
- Added comprehensive JSDoc documentation for all public APIs including:
- Detailed descriptions for all methods and types
- Usage examples for key functions
- Parameter and return type documentation
- Cross-references between related APIs
- Updated `Network` enum to include all supported networks across all network kinds:
- Ethereum networks: MAINNET, SEPOLIA, HOLESKY, HOODI
- OP Stack networks: OP_MAINNET, BASE, WORLDCHAIN, ZORA, UNICHAIN
- Linea networks: LINEA, LINEA_SEPOLIA
- Fixed network enum names to …
=> feat: improve TypeScript type definitions and documentation

ethereum/src/rpc/http_rpc.rs
Using `reqwest::get` in the http rpc appears to leak a small amount of memory. Not exactly sure why that is, but moving to a persistent client removed all persistent leaks according to cargo instruments.
=> fix: http rpc memory leak

Cargo.lock, ethereum/Cargo.toml, ethereum/src/consensus.rs
Rayon seems to cause memory usage to slowly increase. Removing for now.
=> fix: rayon leaking memory
